const strings = {
    heading: 'Create your Profile',
    details:'Complete your profile to unlock the full potential of the app and personalize your experience',
    setup:'Setup Profile',
    profile:'Profile Picture',
    upload:'Upload Photo',
    avatar:'Select Avatar',
    avatarDetails:'Complete your profile to unlock the full potential of the app and personalize your experience',
    continue:'Continue',
    name:'Name',
    phoneNumber:'Phone number',
    emailId:'Email ID',
    checkBox:'I agree to the',
    term:'term of use',
    dob:'Date of Birth',
    gender:'Gender',
    refferal:'Referral Code (Optional)',
    profileModal:'Profile Photo',
    uploadGallery:'Upload from Gallery',
    camera:'Use Camera',
    selectAvatar:'Select an Avatar',
    userName:'Username',
    verifyPhone:'Verify Phone Number',
    enterCode:'Enter the code that we just sent to you on',
    phone:'+1 (619) 436-8218',
    digit:'5-digit Code',
    resend:'Resend',
    password:'Password'
  };
  
  export default strings;